### ISSUE TITLE
Reporte 

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/practica-final-de-hilos-dream-team#2]
[Reporte Hilos - Equipo.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-dream-team/files/6519543/Reporte.Hilos.-.Equipo.pdf)

**Comment by MLR062998** [comment]
calificación: 19/20
califico equipo de javier
 Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Bien hecho y revisado
